---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  handlers:
    - name: rehash rbenv
      shell: rbenv rehash

  tasks: 
    - name: Add brew repository
      shell: 'brew tap {{item}}'
      ignore_errors: true
      with_items:
        - "caskroom/cask"
        - "caskroom/versions"
        - "caskroom/homebrew-cask"

    - name: install homebrew cask
      command: brew install caskroom/cask/brew-cask

    - name: Install development tools
      shell: 'brew install {{item.name}} {{item.option}}'
      ignore_errors: true
      with_items:
        - {name: 'awscli', option: ''}
        - {name: git, option: ''}
        - {name: rbenv, option: ''}
        - {name: ruby-build, option: ''}
        - {name: vim, option: '--with-override-system-vi --with-lua'}
        - {name: tmux, option: ''}
        - {name: reattach-to-user-namespace, option: ''}
        - {name: tig, option: ''}
        - {name: 'postgresql@9.6', option: ''}
        - {name: 'postgresql', option: ''}
        - {name: 'redis', option: ''}

    - name: check ruby version 2.3
      register: exists_ruby23
      shell: rbenv versions --bare | grep 2.3

    - name: install newest ruby version 2.3
      shell: rbenv install $(rbenv install -l | grep -v - | grep 2.3 | tail -1)
      notify: rehash rbenv
      when: exists_ruby23.stdout == ''

    - name: check ruby version 2.4
      register: exists_ruby24
      shell: rbenv versions --bare | grep 2.4

    - name: install newest ruby version 2.4
      shell: rbenv install $(rbenv install -l | grep -v - | grep 2.4 | tail -1)
      notify: rehash rbenv
      when: exists_ruby24.stdout == ''

    - name: Install homebrew casks
      shell: 'brew cask install {{item}}'
      ignore_errors: true
      with_items:
        - alfred
        - atom
        - chromium
        - coteditor
        - dash
        - docker
        - firefox-developer-edition
        - google-chrome
        - google-japanese-ime
        - java
        - karabiner
        - sequel-pro
        - virtualbox
        - vagrant

    - name: install apm packages
      shell: 'apm install {{item}}'
      with_items:
        - atom-ide-ui
        - atom-beautify
        - dracula-ui
        - japanese-menu
        - vim-mode-plus
        - vim-mode-visual-block

    - name: install dein vim
      shell: |
        curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
        sh ./installer.sh ~/

