---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  handlers:
    - name: rehash rbenv
      shell: rbenv rehash
    - name: install vscode extensions
      shell: 'code --install-extension {{ item }}'
      with=items:
        - 'Dart-Code.flutter'
        - 'ms-vsliveshare.vsliveshare'
        - 'vscjava.vscode-maven'
        - 'vscodevim.vim'
        - 'shopify.ruby-extensions-pack'
        - 'shopify.ruby-lsp'
        - 'misogi.ruby-rubocop'
        - 'oderwat.indent-rainbow'
        - 'avetis.tokyo-night'
        - 'pkief.material-icon-theme'
        - 'dracula-theme.theme-dracula'
        - 'esbenp.prettier-vscode'
        - 'eamodio.gitlens'
        - 'vscjava.vscode-gradle'
        - 'ms-ceintl.vscode-language-pack-ja'
        - 'aaron-bond.better-comments'
        - 'gruntfuggly.todo-tree'


  tasks: 
    - name: Add brew repository
      shell: 'brew tap {{item}}'
      ignore_errors: true
      with_items:
        - "caskroom/cask"
        - "caskroom/versions"
        - "caskroom/homebrew-cask"
        - "leoafarias/fvm"

    - name: Install development tools
      shell: 'brew install {{item.name}} {{item.option}}'
      ignore_errors: true
      with_items:
        - {name: awscli, option: ''}
        - {name: git, option: ''}
        - {name: rbenv, option: ''}
        - {name: ruby-build, option: ''}
        - {name: nvim, option: ''}
        - {name: tmux, option: ''}
        - {name: reattach-to-user-namespace, option: ''}
        - {name: tig, option: ''}
        - {name: postgresql@9.6, option: ''}
        - {name: postgresql, option: ''}
        - {name: redis, option: ''}
        - {name: fvm, option: ''}

    - name: check ruby version 3
      register: exists_ruby3
      ignore_errors: true
      shell: rbenv versions --bare | grep 3.3.5

    - name: install newest ruby version 3
      shell: rbenv install $(rbenv install -l | grep -v - | grep 3.3.5 | tail -1)
      notify: rehash rbenv
      when: exists_ruby3.stdout == ''

    - name: Install homebrew casks
      shell: 'brew install -cask {{item}}'
      ignore_errors: true
      with_items:
        - alfred
        - coteditor
        - google-japanese-ime
        - java
        - karabiner-elements
        - sequel-pro
        - virtualbox
        - vagrant
        - android-studio
        - slack
        - microsoft-teams
        - zoom

    - name: install vscode
      shell: 'brew install --cask visual-studio-code'
      notify: install vscode extensions
